openapi: 3.0.3
info:
  title: ticket service
  description: ticket - soa lab 1
  version: 1.0.0

tags:
  - name: Booking
    description: Booking operations


paths:
  /booking/sell/vip/{ticketId}/{personId}:
    post:
      parameters:
        - in: path
          name: ticketId
          schema:
            type: integer
          required: true
          description: ticket id
        - in: path
          name: personId
          schema:
            type: string
          required: true
          description: person id
      tags:
        - Booking
      summary: Create VIP ticket
      description: Скопировать указанный билет, создав такой же, но с категорией "VIP" и с удвоенной ценой
      responses:
        '201':
          description: Event has created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /booking/sell/discount/{ticketId}/{personId}/{discount}:
    post:
      parameters:
        - in: path
          name: ticketId
          schema:
            type: integer
          required: true
          description: ticket ID
        - in: path
          name: personId
          schema:
            type: integer
          required: true
          description: person id
        - in: path
          name: discount
          schema:
            type: integer
          required: true
          description: discount
      tags:
        - Booking
      summary: Create discount ticket
      description: Cоздать новый билет на основе указанного, указав скидку в заданное число %, и, одновременно, увеличив цену билета на ту же самую сумму
      responses:
        '201':
          description: Event has created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  responses:
    ListOfTicketsResponse:
      description: List of tickets
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Ticket'
            json:
              name: Results

    ListOfEventsResponse:
      description: List of events
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Event'
            json:
              name: Results

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
                  example: field xxx must be greater than
                  json:
                    name: Error
          json:
            name: Results

    NotFoundError:
      description: Not found error
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
                  example: entity with id 12 not found
                  json:
                    name: Error
          json:
            name: Results

  parameters:
    TicketFilterParam:
      name: filter
      in: query
      required: false
      description: ' `<field>[<op>]=<value>` where <field> is one of Event field and <op> is one of `(eq|ne|gt|lt|lte|gte)`'
      schema:
        type: array
        items:
          type: string
          example: id[eq]=1
          pattern: '^(id|name|coordinates\.x|coordinates\.y|creationDate|price|discount|refundable|type|event)\[(eq|ne|gt|lt|lte|gte)\]=.+$'

    TicketSortParam:
      name: sort
      in: query
      description: '`[-]<field>` to sort by `<field>`.'
      schema:
        type: string
        pattern: '^-?(id|name|coordinates\.x|coordinates\.y|creationDate|price|discount|refundable|type|event)$'
        example: -name

    EventFilterParam:
      name: filter
      in: query
      required: false
      description: ' `<field>[<op>]=<value>` where <field> is one of Ticket field and <op> is one of `(eq|ne|gt|lt|lte|gte)`'
      schema:
        type: array
        items:
          type: string
          example: id[eq]=1
          pattern: '^(id|name|date|minAge|eventType)\[(eq|ne|gt|lt|lte|gte)\]=.+$'

    EventSortParam:
      name: sort
      in: query
      description: '`[-]<field>` to sort by `<field>`.'
      schema:
        type: string
        pattern: '^-?(id|name|date|minAge|eventType)$'
        example: -date
      
    TicketIdParam:
      name: ticketId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
        
    EventIdParam:
      name: eventnId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
        
  schemas:
    Ticket:
      type: object
      required:
        - name
        - coordinates
        - price
        - discount
        - refundable
        - event
      properties:
        id:
          type: integer
          minimum: 1
          readOnly: true
        name:
          type: string
          nullable: false
          example: "Концерт Доры"
        coordinates:
          nullable: false
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date
          readOnly: true
          nullable: false
          example: '2023-12-13'
        price:
          nullable: false
          type: number
          format: double
          example: 5000.0
          minimum: 1
        discount:
          type: number
          format: double
          nullable: false
          minimum: 0
          exclusiveMinimum: true
          example: 0.0
          maximum: 100
        refundable:
          nullable: false
          example: false
          type: boolean
        type:
          $ref: '#/components/schemas/TicketType'
        event:
          nullable: false
          $ref: '#/components/schemas/Event'

    Coordinates:
      type: object
      required:
        - x
        - y
      properties:
        x:
          example: 100
          type: integer
          nullable: false
          exclusiveMinimum: true
          minimum: -686
        y:
          nullable: false
          type: integer
          example: 100

    Event:
      type: object
      required:
        - name
        - minAge
      properties:
        id:
          type: integer
          nulable: false
          minimum: 1
          readOnly: true
          description: 'Should be unique'
        name:
          type: string
          minLength: 1
          example: 'Концерт Доры'
          nullable: false
        date:
          type: string
          format: date
          example: '2023-12-13'
        minAge:
          type: integer
          example: 12
          nullable: false
        eventType:
          $ref: '#/components/schemas/EventType'

    TicketType:
      type: string
      example: USUAL
      enum:
        - VIP
        - USUAL
        - BUDGETARY
        - CHEAP

    EventType:
      type: string
      example: CONCERT
      enum:
        - CONCERT
        - BASEBALL
        - BASKETBALL
        - THEATRE_PERFORMANCE
