openapi: 3.0.3
info:
  title: ticket service
  description: ticket - soa lab 1
  version: 1.0.0


tags:
  - name: Tickets
    description: Ticket operations
  - name: Events
    description: Event operations
  - name: Booking
    description: Booking operations


paths:
  /ticket:
    get:
      summary: Get all tickets
      tags:
        - Tickets
      parameters:
        - $ref: '#/components/parameters/TicketFilterParam'
        - $ref: '#/components/parameters/TicketSortParam'
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            example: 10
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            example: 0
          required: False
      responses:
        '200':
          $ref: '#/components/responses/ListOfTicketsResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
          
    post:
      summary: Create a new ticket
      tags:
        - Tickets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
          
      responses:
        '201':
          description: Ticket was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
            
        '400':
          $ref: '#/components/responses/ErrorResponse'

  /ticket/{ticketId}:
    get:
      summary: Get ticket by ID
      tags:
        - Tickets
      parameters:
        - $ref: '#/components/parameters/TicketIdParam'
        
      responses:
        '200':
          description: The ticket
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '404':
          description: Ticket not found

    put:
      summary: Update a ticket by ID
      tags:
        - Tickets
      parameters:
        - $ref: '#/components/parameters/TicketIdParam'
        - name: ticket
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Ticket'

      responses:
        '200':
          description: Ticket was updated successfully
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          description: Ticket not found

    delete:
      summary: Delete the ticket by ID
      tags:
        - Tickets
      parameters:
        - $ref: '#/components/parameters/TicketIdParam'
      responses:
        '204':
          description: Ticket has deleted successfully
        '404':
          description: Ticket not found

  /event:
    get:
      summary: Get all events
      tags:
        - Events
      parameters:
        - $ref: '#/components/parameters/EventFilterParam'
        - $ref: '#/components/parameters/EventSortParam'
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            example: 10
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            example: 0
          required: False
      responses:
        '200':
          $ref: '#/components/responses/ListOfEventsResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'

    post:
      summary: Create a new event
      tags:
        - Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event has created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/ErrorResponse'

  /event/{event-id}:
    get:
      summary: Get event by ID
      tags:
        - Events
      parameters:
        - $ref: '#/components/parameters/EventIdParam'

      responses:
        '200':
          description: A event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found

    put:
      summary: Update event by ID
      tags:
        - Events
      parameters:
        - $ref: '#/components/parameters/EventIdParam'
        - name: event
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Event'

      responses:
        '200':
          description: Event updated successfully
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          description: Event not found

    delete:
      summary: Delete event by ID
      tags:
        - Events
      parameters:
        - $ref: '#/components/parameters/EventIdParam'
      responses:
        '204':
          description: Event deleted successfully
        '404':
          description: Event not found


  /booking/sell/vip/{ticket-id}/{person-id}:
    post:
      parameters:
        - in: path
          name: ticket-id
          schema:
            type: integer
          required: true
          description: ticket id
        - in: path
          name: person-id
          schema:
            type: string
          required: true
          description: person id
      tags:
        - Booking
      summary: Create VIP ticket
      description: Скопировать указанный билет, создав такой же, но с категорией "VIP" и с удвоенной ценой
      responses:
        '201':
          description: Event has created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
         $ref: '#/components/responses/ErrorResponse'

  /booking/sell/discount/{ticket-id}/{person-id}/{discount}:
    post:
      parameters:
        - in: path
          name: ticket-id
          schema:
            type: integer
          required: true
          description: ticket ID
        - in: path
          name: person-id
          schema:
            type: integer
          required: true
          description: person id
        - in: path
          name: discount
          schema:
            type: integer
          required: true
          description: discount
      tags:
        - Booking
      summary: Create discount ticket
      description: Cоздать новый билет на основе указанного, указав скидку в заданное число %, и, одновременно, увеличив цену билета на ту же самую сумму
      responses:
        '201':
          description: Event has created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
           $ref: '#/components/responses/ErrorResponse'
  
  /ticket/count-by-type:
    get:
      summary: Calculate the sum of tickets for given ticket type
      tags:
        - Tickets
      parameters:
        - name: type
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/TicketType'
      responses:
        '200':
          description: The sum of tickets for given ticket type
          content:
            application/json:
              schema:
                type: integer
                example: 1235
                json:
                  name: Sum
        '400':
          $ref: '#/components/responses/ErrorResponse'

  /ticket/sum-discount:
    get:
      summary: Calculate the sum of discount for all tickets
      tags:
        - Tickets
      responses:
        '200':
          description: The sum of discount for all tickets
          content:
            application/json:
              schema:
                type: double
                example: 123.5
                json:
                  name: Sum
        '400':
          $ref: '#/components/responses/ErrorResponse'

  /ticket/count-by-discount:
    get:
      summary: Count tickets by discount
      tags:
        - Tickets
      responses:
        '200':
          description: The count of tickets groupped by discount
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    discount:
                      type: integer
                      format: int32
                      example: 10
                    count:
                      type: integer
                      example: 100
        '400':
          $ref: '#/components/responses/ErrorResponse'
          
components:
  responses:
    ListOfTicketsResponse:
      description: List of tickets
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Ticket'
            json:
              name: Results

    ListOfEventsResponse:
      description: List of events
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Event'
            json:
              name: Results

    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
              example: Bad request
              json:
                name: Error
            json:
              name: Results
    
  parameters:
    TicketFilterParam:
      name: ticketFilter
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          example: id[eq]=1
          pattern: '^(id|name|coordinates\.x|coordinates\.y|creationDate|price|discount|refundable|type|event)\[(eq|ne|gt|lt|lte|gte)\]=.+$'

    TicketSortParam:
      name: ticketSort
      in: query
      schema:
        type: string
        pattern: '^-?(id|name|coordinates\.x|coordinates\.y|creationDate|price|discount|refundable|type|event)$'
        example: -name

    EventFilterParam:
      name: eventFilter
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          example: id[eq]=1
          pattern: '^(id|name|date|minAge|eventType)\[(eq|ne|gt|lt|lte|gte)\]=.+$'

    EventSortParam:
      name: eventSort
      in: query
      schema:
        type: string
        pattern: '^-?(id|name|date|minAge|eventType)$'
        example: -date
      
    TicketIdParam:
      name: ticketId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
        
    EventIdParam:
      name: eventnId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
        
  schemas:
    Ticket:
      type: object
      required:
        - name
        - coordinates
        - price
        - discount
        - refundable
        - event
      properties:
        id:
          type: integer
          minimum: 1
          readOnly: true
        name:
          type: string
          nullable: false
          example: "Концерт Доры"
        coordinates:
          nullable: false
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date
          readOnly: true
          nullable: false
          example: '2023-12-13'
        price:
          nullable: false
          type: number
          format: double
          example: 5000.0
          minimum: 1
        discount:
          type: number
          format: double
          nullable: false
          minimum: 0
          exclusiveMinimum: true
          example: 0.0
          maximum: 100
        refundable:
          nullable: false
          example: false
          type: boolean
        type:
          $ref: '#/components/schemas/TicketType'
        event:
          nullable: false
          $ref: '#/components/schemas/Event'

    Coordinates:
      type: object
      required:
        - x
        - y
      properties:
        x:
          example: 100
          type: integer
          nullable: false
          exclusiveMinimum: true
          minimum: -686
        y:
          nullable: false
          type: integer
          example: 100

    Event:
      type: object
      required:
        - name
        - minAge
      properties:
        id:
          type: integer
          nulable: false
          minimum: 1
          readOnly: true
          description: 'Should be unique'
        name:
          type: string
          minLength: 1
          example: 'Концерт Доры'
          nullable: false
        date:
          type: string
          format: date
          example: '2023-12-13'
        minAge:
          type: integer
          example: 12
          nullable: false
        eventType:
          $ref: '#/components/schemas/EventType'

    TicketType:
      type: string
      example: USUAL
      enum:
        - VIP
        - USUAL
        - BUDGETARY
        - CHEAP

    EventType:
      type: string
      example: CONCERT
      enum:
        - CONCERT
        - BASEBALL
        - BASKETBALL
        - THEATRE_PERFORMANCE
