version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=studs
    ports:
      - '5432:5432'

  admin:
    image: adminer
    depends_on:
      - db
    ports:
      - '9999:8080'

  haproxy:
    image: "haproxy:2.2-alpine"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/cors.lua:/usr/local/etc/haproxy/cors.lua
      - ./haproxy/mydomain.pem:/usr/local/etc/haproxy/ssl/mydomain.pem

  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    environment:
      - 'CONSUL_LOCAL_CONFIG={"server": true}'
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0

networks:
  consul: {}

