version: "3.3"

services:
  db:
    container_name: demo_postgres
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
  pgadmin:
    container_name: demo_pgadmin
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.ru
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"